services:
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs/conf:/etc/letsencrypt:ro
    networks:
      - keycloak-network
    depends_on:
      - keycloak

  certbot:
    image: certbot/dns-cloudflare:latest
    container_name: certbot
    restart: on-failure
    volumes:
      - ./certs/conf:/etc/letsencrypt
      - ./certs/secrets/cloudflare.ini:/etc/letsencrypt/secrets/cloudflare.ini:ro
    command: >
      certonly
      --dns-cloudflare
      --dns-cloudflare-credentials /etc/letsencrypt/secrets/cloudflare.ini
      --email eamarilla@creminox.com
      --agree-tos
      --no-eff-email
      --non-interactive
      -d login.intranetcreminox.com
    networks:
      - keycloak-network

  keycloak:
    image: quay.io/keycloak/keycloak:26.7.0
    container_name: keycloak
    restart: always
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: Ki?6#p&2e#NL+%Y8
      KC_DB: mysql
      KC_DB_URL_HOST: db
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: root
      KC_DB_PASSWORD: x!yCR9!2}u6e@03N
      KC_HOSTNAME: login.intranetcreminox.com
      KC_HOSTNAME_PROTOCOL: https
      KC_HOSTNAME_PORT: 443
      KC_HTTP_ENABLED: "true"
      KC_PROXY: reencrypt
      KC_PROXY_HEADERS: forwarded,xforwarded
      KC_METRICS_ENABLED: "true"
    command: start
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - keycloak-network

  db:
    image: mysql:8.0
    container_name: keycloak_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: x!yCR9!2}u6e@03N
      MYSQL_DATABASE: keycloak
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - keycloak-network

networks:
  keycloak-network:
    driver: bridge

volumes:
  db-data:
    driver: local