parent=keycloak.v2

import=common/keycloak

styles=css/style.css

# Form classes
kcFormGroupClass=form-group
kcLabelClass=form-label
kcInputClass=form-control
kcInputErrorMessageClass=form-error-message
kcFormSettingClass=form-setting
kcFormOptionsWrapperClass=form-options-wrapper
kcButtonClass=btn
kcButtonPrimaryClass=btn-primary
kcButtonLargeClass=btn-lg
kcButtonSecondaryClass=btn-secondary
kcButtonBlockClass=btn-block

# Header/Container
kcHeaderWrapperClass=header-wrapper
kcHeaderClass=header-class

# Other classes
kcSocialProvidersClass=social-providers-wrapper
kcFormSocialAccountSectionClass=social-section
kcFormSocialAccountListClass=social-list
kcFormSocialAccountListButtonClass=social-list-button
kcFormSocialAccountNameClass=social-name
kcSignUpClass=signup-section
kcInfoAreaWrapperClass=info-wrapper