parent=keycloak.v2

import=common/keycloak

styles=css/style.css

# Custom properties for CREMINOX theme
kcHtmlClass=login-pf-creminox
kcBodyClass=login-pf-body-creminox
kcLoginClass=pf-v5-c-login-creminox
kcFormCardClass=pf-v5-c-card-creminox
kcHeaderWrapperClass=kc-logo-creminox
