version = 5.7.0
archive_dir = /etc/letsencrypt/archive/login.intranetcreminox.com
cert = /etc/letsencrypt/live/login.intranetcreminox.com/cert.pem
privkey = /etc/letsencrypt/live/login.intranetcreminox.com/privkey.pem
chain = /etc/letsencrypt/live/login.intranetcreminox.com/chain.pem
fullchain = /etc/letsencrypt/live/login.intranetcreminox.com/fullchain.pem
[renewalparams]
account = 3e0989e7562cfd3d1e96c80a146122e5
authenticator = dns-cloudflare
dns_cloudflare_credentials = /etc/letsencrypt/secrets/cloudflare.ini
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[acme_renewal_info]
ari_retry_after = 2026-07-17T21:44:33
